version: 1.0.{build}
image: Visual Studio 2017
shallow_clone: true
environment:
  AWS_ACCESS_KEY_ID: AKIAICLKLZT3ZYS6KQPQ
  AWS_SECRET_ACCESS_KEY:
    secure: HbbMjf0hSbFBvQiEYP27SKtBfOZzZLYtS9cMzQFBbjabk4gLl/eRIQsQ7oPXPDqE
  AWS_DEFAULT_REGION: eu-west-1
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: Any CPU
configuration: Release
before_build:
- cmd: nuget restore
build_script:
  - msbuild Dummy.WebApi.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Package /p:PackageLocation=%APPVEYOR_BUILD_FOLDER%\%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%.zip
  - appveyor PushArtifact %APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%.zip -Type WebDeployPackage
cache:
  - packages -> **\packages.config
build:
  publish_wap: true
  verbosity: minimal
deploy:
- provider: S3
  access_key_id: AKIAICLKLZT3ZYS6KQPQ
  secret_access_key:
    secure: HbbMjf0hSbFBvQiEYP27SKtBfOZzZLYtS9cMzQFBbjabk4gLl/eRIQsQ7oPXPDqE
  region: eu-west-1
  bucket: eb-dotnet-spike
  folder: builds
  encrypt: false
after_deploy:
- cmd: aws elasticbeanstalk create-application-version --application-name eb-dotnet-spike --version-label %APPVEYOR_BUILD_VERSION% --description eb-dotnet-spike-%APPVEYOR_BUILD_VERSION% --source-bundle S3Bucket="eb-dotnet-spike",S3Key="builds/%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%.zip"
